# fly.toml app configuration file generated for javascript-dom on 2025-03-01T23:58:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'javascript-dom'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
